### ISSUE TITLE
Incrementally Dumping Outputs to a File

### ISSUE THREAD

**Issue by VisenDev** [lassade/profiler.zig#2]
It would be nice if the profiler were periodically dump its data to the output file rather than all at once when the process closes. 

This would have several benefits:
- It would reduce the memory used by the profiler.
- It would fix applications "freezing" during shutdown because of the profiler logging results. When fps testing a game at around ~1200 fps for a minute or so, the window becomes unresponsive for several minutes when I close the application. Incrementally dumping partial records to a file would prevent this from happening all at once

**Comment by lassade** [comment]
Hi @VisenDev, I just updated the profile.zig with a better output mechanism, it should be fairly simple to implement a periodically dump.

I also added a less than ideal (you shouldn't use it) profile_file.zig that outputs straight to a json file, that you can take some ideas from.

**Comment by lassade** [comment]
The dump can done at each `frameMark`, so only a single frame must be kept in memory

**Comment by lassade** [comment]
Take a look in the new profile_file.zig, it provides this functionality, but it adds a big overhead :( per frame
